"""Shared helper: render the Delta-rho isosurface for the hero drug/2D-material
complex and drop it onto a house-style single-panel figure.

Rendering priority: ChimeraX (GPU, soft surfaces) -> PyMOL (CPU ray trace) ->
a "render unavailable" placeholder. The Delta-rho cube ships gzipped in
results/quantum/drho/; it is regenerated by build_deltarho.py.
"""
import os, gzip, shutil, tempfile
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

try:
    import _pubstyle
except Exception:
    _pubstyle = None
try:
    import _chimerax
except Exception:
    _chimerax = None
try:
    import _pymol
except Exception:
    _pymol = None


def _autocrop(png, pad=24):
    try:
        from PIL import Image, ImageChops
        im = Image.open(png).convert("RGB")
        bg = Image.new("RGB", im.size, (255, 255, 255))
        bbox = ImageChops.difference(im, bg).getbbox()
        if bbox:
            l, t, r, b = bbox
            l = max(0, l - pad); t = max(0, t - pad)
            r = min(im.width, r + pad); b = min(im.height, b + pad)
            im.crop((l, t, r, b)).save(png)
    except Exception:
        pass


def _gunzip(gz):
    fd, path = tempfile.mkstemp(suffix=".cub")
    os.close(fd)
    with gzip.open(gz, "rb") as fi, open(path, "wb") as fo:
        shutil.copyfileobj(fi, fo)
    return path


def render_isosurface(drho_dir, key, out_png, level, turn=(0, 0, 0),
                      cache=True):
    """Render <key>_deltarho.cub(.gz) + <key>_complex.xyz -> out_png."""
    if cache and os.path.exists(out_png):
        _autocrop(out_png)
        return out_png
    struct = os.path.join(drho_dir, f"{key}_complex.xyz")
    cub = os.path.join(drho_dir, f"{key}_deltarho.cub")
    tmp = None
    if not os.path.exists(cub) and os.path.exists(cub + ".gz"):
        cub = tmp = _gunzip(cub + ".gz")
    try:
        if _chimerax and _chimerax.AVAILABLE:
            _chimerax.drho_figure(struct, cub, out_png, level=level, turn=turn)
        elif _pymol and getattr(_pymol, "AVAILABLE", False):
            _pymol.drho_figure(struct, cub, out_png, level=level,
                               orient_on_carrier=False, tilt=0, turn=turn)
        else:
            return None
    finally:
        if tmp and os.path.exists(tmp):
            os.remove(tmp)
    if os.path.exists(out_png):
        _autocrop(out_png)
        return out_png
    return None


def compose(out_fig, render_png, fig_no, title, drug, carrier, level,
            dEint_kcal=None, dq_e=None, extra=None):
    fig, ax = plt.subplots(figsize=(6.6, 5.2))
    ax.set_xticks([]); ax.set_yticks([])
    ax.set_anchor("N")
    for s in ax.spines.values():
        s.set_visible(False)
    if render_png and os.path.exists(render_png):
        ax.imshow(mpimg.imread(render_png), aspect="equal")
    else:
        ax.text(0.5, 0.5, "render unavailable", ha="center", va="center",
                transform=ax.transAxes)
    muted = getattr(_pubstyle, "MUTED", "#666666")
    bits = [f"GFN2-xTB densities, $\\Delta\\rho$ = $\\rho_{{complex}}$ - $\\rho_{{carrier}}$ - $\\rho_{{drug}}$",
            f"isovalue $\\pm${level:g} e bohr$^{{-3}}$; yellow = electron gain, blue = electron loss"]
    e2 = []
    if dEint_kcal is not None:
        e2.append(f"$\\Delta E_{{int}}$ = {dEint_kcal:.1f} kcal mol$^{{-1}}$")
    if dq_e is not None:
        e2.append(f"$\\Delta Q$ = +{dq_e:.2f} e")
    if e2:
        bits.append(" · ".join(e2))
    if extra:
        bits.append(extra)
    ax.text(0.5, -0.02, "\n".join(bits), ha="center", va="top", fontsize=7.8,
            color=muted, transform=ax.transAxes)
    fig.suptitle(f"Figure {fig_no}. {title}", fontsize=10.5,
                 fontweight="bold", y=0.985)
    fig.subplots_adjust(top=0.93, bottom=0.16, left=0.03, right=0.97)
    if _pubstyle:
        _pubstyle.save(fig, out_fig, also_pdf=False)
    else:
        fig.savefig(out_fig, dpi=400)
    plt.close(fig)
    return out_fig
